[fairu.management]
allowed-usernames = [ "melike2d" ]

[fairu.server]
host = "0.0.0.0"
port = 3232

[fairu.s3]
path-style-access-enabled = true
endpoint   = "https://s3.2d.gay"
region     = "us-west-2"
bucket     = "fairu"
access-key = ""
secret-key = ""

bucket = "fairu"
region = "us-west-2"

[fairu.jwt]
secret = "super secret key"

[fairu.db]
uri           = "mongodb://127.0.0.1:27017"
database-name = "fairu"
